### ISSUE TITLE
Code Question on Chapter 17 (State Management and Persistence)

### ISSUE THREAD

**Issue by lukewyman** [ReactiveDesignPatterns/CodeSamples#2]
1) I understand the book is still a MEAP, but if the code for chapter 17 happens to be complete, can it be updated here?
2) If the answer to 1) is no, then can you clarify these thoughts on identity?
a) It seems the id: Long in ManagerCommand is an id for the message, NOT the shopping cart. So several ManagerCommands could be sent to a particular shopping cart. They'd all have the same URI in the ShoppingCartRef, but each would have its own id: Long to identify that particular message. Probably so that the sender can track the  ManagerCommands it sends so that it can correlate them should pertinent replies return later?
b) It makes a lot of sense to use a URI as an identifier for a domain entity (Shopping Cart), since the term "URI" clearly is about identity. The question though becomes how to make each URI for each shopping cart unique, which in turn suggests introducing something like a Long into the URI, say `http://myapp.com/shoppingcarts/143`. Firstly, what is a good approach to making each URI have that piece of uniqueness, and then secondly, the finer point, how should people like myself who are used to RDBMS databases generating IDs for them in classic n-tier monoliths? Would a UUID answer my own question? - example: `http://myapp.com/shoppingcarts/gobbledygookofUUIDgoeshere`

**Comment by rkuhn** [comment]
Thanks for raising these questions, and sorry for the delay @lukewyman! The repository had not been updated with the chapter structure a few months ago, things should be in the right places now.

I’ll keep your questions in mind when reviewing the manuscript to ensure that they are answered.

**Comment by rkuhn** [comment]
Hmm, I should probably answer here as well:

2a) Yes.

2b) Yes, UUID is a decentralized solution that scales well; if meaningful or contiguous identifiers are required then that will usually force the introduction of a central ID generation service—with the downside of then depending on that service’s availability.
