### ISSUE TITLE
Unable to build chapters 13-14

### ISSUE THREAD

**Issue by phderome** [ReactiveDesignPatterns/CodeSamples#3]
Not sure if I should research this on my own rather than the author as it is probably simple, but anyhow.

I forked the project, downloaded and issued `sbt compile`. I have same errors compiling from Intellij IDEA CE 2016.3 (requested to Intelllij to create straight from my github fork URL using sources and didn't "tweak" anything in IDE thereafter) or straight from OSX 10.12.3 Sierra shell.

**Notes**: 

- I've been in the habit of doing Scala development on this computer for a year+ without a problem but I don't do Java so I could be missing Java artefacts of some kind.

- I also found two pom.xml files in ch2, not sure whether I should use them in some way (mvn).

`sbt about`
\>[info] This is sbt 0.13.8
\>[info] The current project is {file:/Users/philippederome/workspace/CodeSamples2/}codesamples2 0.1-SNAPSHOT
\>[info] The current project is built against Scala 2.11.6
\>[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, spray.boilerplate.BoilerplatePlugin
\>[info] sbt, sbt plugins, and build definitions are using Scala 2.10.4
 
MacBook-Pro-2:CodeSamples2 philippederome$ `javac -version`
javac 1.8.0_91
MacBook-Pro-2:CodeSamples2 philippederome$ `scalac -version`
Scala compiler version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL
MacBook-Pro-2:CodeSamples2 philippederome$ `which java`
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java
MacBook-Pro-2:CodeSamples2 philippederome$ `which scala`
/Applications/scala-2.11.7/bin/scala
MacBook-Pro-2:CodeSamples2 philippederome$ 

MacBook-Pro-2:CodeSamples2 philippederome$ `sbt`
[info] Loading project definition from /Users/philippederome/workspace/CodeSamples2/project
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/project/}codesamples2-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/philippederome/workspace/CodeSamples2/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to codesamples2 (in build file:/Users/philippederome/workspace/CodeSamples2/)
> compile
[info] Generating 'Scoped.scala'
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}codesamples2...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}common...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter07...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter15...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter14...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter02...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter17...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter16...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter13...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter12...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Resolving com.typesafe.akka#akka-actor_2.11;2.4.1 ...
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.akka:akka-stream-experimental_2.11:1.0 -> 2.0.1
[warn]  * com.typesafe.akka:akka-actor_2.11:2.3.12 -> 2.4.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving org.scala-lang.modules#scala-async_2.11;0.9.2 ...
[info] Updating {file:/Users/philippederome/workspace/CodeSamples2/}chapter04...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving com.typesafe.akka#akka-contrib_2.11;2.4.1 ...
[info] Compiling 4 Scala sources to /Users/philippederome/workspace/CodeSamples2/common/target/scala-2.11/classes...
[info] Resolving org.scala-sbt#io_2.11;0.13.8 ...
[warn]  module not found: org.scala-sbt#io_2.11;0.13.8
[warn] ==== local: tried
[warn]   /Users/philippederome/.ivy2/local/org.scala-sbt/io_2.11/0.13.8/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scala-sbt/io_2.11/0.13.8/io_2.11-0.13.8.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-sbt#io_2.11;0.13.8: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] Resolving org.scala-lang#scala-library;2.11.6 ...
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          org.scala-sbt:io_2.11:0.13.8 (/Users/philippederome/workspace/CodeSamples2/chapter13/build.sbt#L3-4)
[warn]            +- com.reactivedesignpatterns:chapter13_2.11:0.1-SNAPSHOT
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.akka:akka-stream-experimental_2.11:1.0 -> 2.0.1
[warn]  * com.typesafe.akka:akka-actor_2.11:2.3.12 -> 2.4.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.akka:akka-stream-experimental_2.11:1.0 -> 2.0.1
[warn]  * com.typesafe.akka:akka-actor_2.11:2.3.12 -> 2.4.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.typesafe.akka:akka-actor_2.11:2.3.12 -> 2.4.1
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.6, 2.11.1) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] one warning found
[info] Compiling 2 Scala sources to /Users/philippederome/workspace/CodeSamples2/chapter04/target/scala-2.11/classes...
[info] Compiling 7 Scala sources to /Users/philippederome/workspace/CodeSamples2/chapter17/target/scala-2.11/classes...
[info] Compiling 4 Java sources to /Users/philippederome/workspace/CodeSamples2/chapter14/target/scala-2.11/classes...
[info] Compiling 6 Scala sources and 1 Java source to /Users/philippederome/workspace/CodeSamples2/chapter15/target/scala-2.11/classes...
[info] Compiling 1 Scala source to /Users/philippederome/workspace/CodeSamples2/chapter07/target/scala-2.11/classes...
[info] Compiling 5 Scala sources to /Users/philippederome/workspace/CodeSamples2/chapter16/target/scala-2.11/classes...
[error] /Users/philippederome/workspace/CodeSamples2/chapter14/src/main/java/com/reactivedesignpatterns/chapter14/ComplexCommand.java:204: method toMat in class akka.stream.javadsl.Source<Out,Mat> cannot be applied to given types;
[error]   required: akka.stream.Graph<akka.stream.SinkShape<com.reactivedesignpatterns.chapter14.ComplexCommand.DataElement>,M>,akka.japi.function.Function2<scala.runtime.BoxedUnit,M,M2>
[error]   found: akka.stream.javadsl.Sink<com.reactivedesignpatterns.chapter14.ComplexCommand.DataElement,scala.concurrent.Future<java.lang.Long>>,scala.Function2<scala.runtime.BoxedUnit,java.lang.Long,java.lang.Long>
[error]   reason: cannot infer type-variable(s) M,M2,U,In
[error]     (argument mismatch; scala.Function2<scala.runtime.BoxedUnit,java.lang.Long,java.lang.Long> cannot be converted to akka.japi.function.Function2<scala.runtime.BoxedUnit,M,M2>)
[error] Source.<DataElement>empty()
[error]                         .filter(new InRange("year", 1950, 1960))
[error]                         .toMat
[warn] /Users/philippederome/workspace/CodeSamples2/chapter15/src/main/scala/com/reactivedesignpatterns/chapter15/AskPattern.scala:77: match may not be exhaustive.
[warn] It would fail on the following inputs: Sig(_, Failed(_, _)), Sig(_, PostRestart(_)), Sig(_, PostStop), Sig(_, PreRestart(_)), Sig(_, Terminated(_))
[warn]           val childActor = ctx.spawnAnonymous(Props(FullTotal[SendEmailResult] {
[warn]                                                                                ^
[warn] /Users/philippederome/workspace/CodeSamples2/chapter15/src/main/scala/com/reactivedesignpatterns/chapter15/Saga.scala:73: match may not be exhaustive.
[warn] It would fail on the following input: RolledBack
[warn]           last match {
[warn]           ^
[warn] two warnings found
[trace] Stack trace suppressed: run last chapter13/*:update for the full output.
**[error] (chapter14/compile:compileIncremental) javac returned nonzero exit code
[error] (chapter13/*:update) sbt.ResolveException: unresolved dependency: org.scala-sbt#io_2.11;0.13.8: not found**
[error] Total time: 16 s, completed 19-Mar-2017 8:51:26 PM
>

**Comment by rkuhn** [comment]
Sorry for the long delay; I have just tried it and to my astonishment I can reproduce it—I cannot believe that I pushed something that was not compiling at the time … In any case, I’ll look into this now (already downloading the new version of the internet).

**Comment by rkuhn** [comment]
Updated Scala/Akka and fixed some broken things, should work now.

**Comment by phderome** [comment]
oh, thanks, I'll refork from scratch and try again.
