### ISSUE TITLE
rename chapter04 to chapter11

### ISSUE THREAD

**Issue by phderome** [ReactiveDesignPatterns/CodeSamples#4]
github chapter04 corresponds to book's chapter11. Perhaps book organization changed after code was prepared.

**Comment by phderome** [comment]
If it is confirmed to be a rather trivial exercise, I can volunteer a PR to address this issue.

**Comment by rkuhn** [comment]
Thanks for noticing, a PR would be most welcome!

**Comment by phderome** [comment]
I can do that once the other PR is approved. _Not sure how to manage git with forks with 2 independent PRs on the go._ hence postponing.

**Comment by rkuhn** [comment]
Thanks a lot for your help! Today and tomorrow I'll be traveling, but then I should finally have some time for my private projects again.

**Comment by phderome** [comment]
see latest [PR 10](https://github.com/ReactiveDesignPatterns/CodeSamples/pull/10)

**Comment by phderome** [comment]
PR merged.
